name: Octo Organization CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from Octo Organization
        env: 
          test: ${{secrets.test}}
          DATASETS_ACCESS_KEY:  ${{secrets.DATASETS_ACCESS_KEY}}
        
