name: Composite Images
on: [push, pull_request]
jobs:
  composite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ImageMagick
        run: ./install_imagemagick.sh
      
      - name: Composite Images
        env:
          LOGO_PATH: ${{ secrets.LOGO_PATH }}
          BACKGROUND_PATH: ${{ secrets.BACKGROUND_PATH }}
        run: |
          # Composite images using ImageMagick
          composite -gravity center "$LOGO_PATH" "$BACKGROUND_PATH" output.png

      - name: Save Composite Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: composite-image
          path: output.png
